import { Photo, Group, CalendarEvent } from '../types/types';

export const PHOTOS: Photo[] = [
  {
    id: 'p1',
    is_flagged: false,
    url: 'https://images.unsplash.com/photo-1514439827219-9137a0b99245?w=600&auto=format&fit=crop',
    title: 'Neon Skyline',
    created_at: '2026-06-20',
    tags: ['urban', 'night'],
    group_id: 'City Sessions',
    width: 3262,
    height: 4897,
    uploader_id: 'Van Mendoza',
  },
  {
    id: 'p2',
    is_flagged: false,
    url: 'https://images.unsplash.com/photo-1599060052009-24d6d0b0161c?w=600&auto=format&fit=crop',
    title: 'Street Pulse',
    created_at: '2026-06-18',
    tags: ['urban', 'night'],
    group_id: 'City Sessions',
    width: 5978,
    height: 3985,
    uploader_id: 'Hiep Duong',
  },
  {
    id: 'p3',
    is_flagged: false,
    url: 'https://images.unsplash.com/photo-1541702467897-41915a07d3a7?w=600&auto=format&fit=crop',
    title: 'Rain Reflections',
    created_at: '2026-06-15',
    tags: ['urban', 'night', 'abstract'],
    group_id: 'City Sessions',
    width: 2571,
    height: 3856,
    uploader_id: 'Andre Benz',
  },
  {
    id: 'p4',
    is_flagged: false,
    url: 'https://images.unsplash.com/photo-1535391879778-3bae11d29a24?w=600&auto=format&fit=crop',
    title: 'Glass Towers',
    created_at: '2026-06-12',
    tags: ['architecture', 'urban'],
    group_id: 'Architecture Vol. II',
    width: 5860,
    height: 3907,
    uploader_id: 'Irina Iriser',
  },
  {
    id: 'p5',
    is_flagged: false,
    url: 'https://images.unsplash.com/photo-1541537103745-ea3429c65dc4?w=600&auto=format&fit=crop',
    title: 'Rush Hour',
    created_at: '2026-06-10',
    tags: ['urban', 'night'],
    group_id: 'City Sessions',
    width: 2590,
    height: 3885,
    uploader_id: 'Andre Benz',
  },
  {
    id: 'p6',
    is_flagged: false,
    url: 'https://images.unsplash.com/photo-1506863530036-1efeddceb993?w=600&auto=format&fit=crop',
    title: 'Monochrome Muse',
    created_at: '2026-06-08',
    tags: ['portrait'],
    group_id: 'Portraits 2026',
    width: 3813,
    height: 2975,
    uploader_id: 'Rachel McDermott',
  },
  {
    id: 'p7',
    is_flagged: false,
    url: 'https://images.unsplash.com/photo-1606143412458-acc5f86de897?w=600&auto=format&fit=crop',
    title: 'Studio Light',
    created_at: '2026-06-05',
    tags: ['portrait'],
    group_id: 'Portraits 2026',
    width: 5504,
    height: 7706,
    uploader_id: 'Ali Nejatian',
  },
  {
    id: 'p8',
    is_flagged: false,
    url: 'https://images.unsplash.com/photo-1532170579297-281918c8ae72?w=600&auto=format&fit=crop',
    title: 'Contrast Study',
    created_at: '2026-06-03',
    tags: ['portrait', 'abstract'],
    group_id: 'Portraits 2026',
    width: 5923,
    height: 3890,
    uploader_id: 'Kirill Balobanov',
  },
  {
    id: 'p9',
    is_flagged: false,
    url: 'https://images.unsplash.com/photo-1581841064838-a470c740e8ee?w=600&auto=format&fit=crop',
    title: 'Green Dreams',
    created_at: '2026-05-30',
    tags: ['portrait', 'travel'],
    group_id: 'Portraits 2026',
    width: 4000,
    height: 6000,
    uploader_id: 'Andrey Zvyagintsev',
  },
  {
    id: 'p10',
    is_flagged: false,
    url: 'https://images.unsplash.com/photo-1488972685288-c3fd157d7c7a?w=600&auto=format&fit=crop',
    title: 'Upward Gaze',
    created_at: '2026-05-27',
    tags: ['architecture'],
    group_id: 'Architecture Vol. II',
    width: 2400,
    height: 1600,
    uploader_id: 'Anders Jildén',
  },
  {
    id: 'p11',
    is_flagged: false,
    url: 'https://images.unsplash.com/photo-1531591022136-eb8b0da1e6d0?w=600&auto=format&fit=crop',
    title: 'Geometric Void',
    created_at: '2026-05-24',
    tags: ['architecture', 'abstract'],
    group_id: 'Architecture Vol. II',
    width: 3225,
    height: 2304,
    uploader_id: 'Tobias Keller',
  },
  {
    id: 'p12',
    is_flagged: false,
    url: 'https://images.unsplash.com/photo-1498262257252-c282316270bc?w=600&auto=format&fit=crop',
    title: 'Grid Collapse',
    created_at: '2026-05-21',
    tags: ['abstract', 'architecture'],
    group_id: 'Abstracts',
    width: 3264,
    height: 4896,
    uploader_id: 'Erik Eastman',
  },
  {
    id: 'p13',
    is_flagged: false,
    url: 'https://images.unsplash.com/photo-1632667680404-572c57873c21?w=600&auto=format&fit=crop',
    title: 'Sky Fragment',
    created_at: '2026-05-18',
    tags: ['architecture', 'abstract'],
    group_id: 'Abstracts',
    width: 3024,
    height: 4032,
    uploader_id: 'David Underland',
  },
  {
    id: 'p14',
    is_flagged: false,
    url: 'https://images.unsplash.com/photo-1604223190546-a43e4c7f29d7?w=600&auto=format&fit=crop',
    title: 'Alpine Light',
    created_at: '2026-05-15',
    tags: ['nature', 'travel'],
    group_id: 'Wild Places',
    width: 6016,
    height: 4016,
    uploader_id: 'Sven Pieren',
  },
  {
    id: 'p15',
    is_flagged: false,
    url: 'https://images.unsplash.com/photo-1501568799193-14077d782cc3?w=600&auto=format&fit=crop',
    title: 'Fog Mountain',
    created_at: '2026-05-12',
    tags: ['nature', 'travel'],
    group_id: 'Wild Places',
    width: 3648,
    height: 2432,
    uploader_id: 'Ivana Cajina',
  },
  {
    id: 'p16',
    is_flagged: false,
    url: 'https://images.unsplash.com/photo-1604223172843-9541457ba7e4?w=600&auto=format&fit=crop',
    title: 'Summit Clouds',
    created_at: '2026-05-09',
    tags: ['nature', 'travel'],
    group_id: 'Wild Places',
    width: 4016,
    height: 6016,
    uploader_id: 'Sven Pieren',
  },
  {
    id: 'p17',
    is_flagged: false,
    url: 'https://images.unsplash.com/photo-1626948688703-0136bc0a90da?w=600&auto=format&fit=crop',
    title: 'Valley Green',
    created_at: '2026-05-06',
    tags: ['nature', 'travel'],
    group_id: 'Wild Places',
    width: 3456,
    height: 5184,
    uploader_id: 'Milo Weiler',
  },
];

export const ALBUMS: Group[] = [
  {
    id: 'a1',
    name: 'City Sessions',
    description: 'Mock description',
    created_by: 'mock-user',
    created_at: '2026-06-01',
  },
  {
    id: 'a2',
    name: 'Portraits 2026',
    description: 'Mock description',
    created_by: 'mock-user',
    created_at: '2026-05-15',
  },
  {
    id: 'a3',
    name: 'Architecture Vol. II',
    description: 'Mock description',
    created_by: 'mock-user',
    created_at: '2026-05-10',
  },
  {
    id: 'a4',
    name: 'Wild Places',
    description: 'Mock description',
    created_by: 'mock-user',
    created_at: '2026-04-20',
  },
  {
    id: 'a5',
    name: 'Abstracts',
    description: 'Mock description',
    created_by: 'mock-user',
    created_at: '2026-04-05',
  },
];

export const EVENTS: CalendarEvent[] = [
  {
    id: 'e1',
    group_id: 'mock-group',
    creator_id: 'mock-user',
    title: 'Golden Hour Shoot',
    event_date: '2026-06-28',
    event_time: '18:30',
    created_at: '2026-06-26T18:00:00Z',
    description: 'Rooftop session with the 85mm f/1.4 — magic hour portraits.',
    color: 'amber',
  },
  {
    id: 'e2',
    group_id: 'mock-group',
    creator_id: 'mock-user',
    title: 'Architecture Walk',
    event_date: '2026-07-02',
    event_time: '07:00',
    created_at: '2026-06-26T18:00:00Z',
    description: 'Downtown district — concrete & glass morning shoot.',
    color: 'cyan',
  },
  {
    id: 'e3',
    group_id: 'mock-group',
    creator_id: 'mock-user',
    title: 'Print Review — Vol II',
    event_date: '2026-07-05',
    event_time: '14:00',
    created_at: '2026-06-26T18:00:00Z',
    description: 'Select and order prints for Architecture Vol. II album.',
    color: 'purple',
  },
  {
    id: 'e4',
    group_id: 'mock-group',
    creator_id: 'mock-user',
    title: 'Night Market Shoot',
    event_date: '2026-07-10',
    event_time: '21:00',
    created_at: '2026-06-26T18:00:00Z',
    description: 'Street photography at Chinatown Night Market.',
    color: 'rose',
  },
  {
    id: 'e5',
    group_id: 'mock-group',
    creator_id: 'mock-user',
    title: 'Client Gallery Delivery',
    event_date: '2026-07-15',
    event_time: '10:00',
    created_at: '2026-06-26T18:00:00Z',
    description: 'Final edits and gallery link delivery for Sophia & James.',
    color: 'teal',
  },
];

export const ALL_TAGS = ['urban', 'portrait', 'nature', 'architecture', 'abstract', 'travel', 'night'] as const;

export const EVENT_COLOR_MAP: Record<string, { bgClass: string; textClass: string; dotClass: string; borderClass: string; shadowClass: string }> = {
  cyan:   { bgClass: 'bg-cyan-primary/12', textClass: 'text-cyan-primary', dotClass: 'bg-cyan-primary', borderClass: 'border-cyan-primary/20', shadowClass: 'shadow-glow-xs-cyan' },
  purple: { bgClass: 'bg-purple/15',       textClass: 'text-purple',       dotClass: 'bg-purple',       borderClass: 'border-purple/20',       shadowClass: 'shadow-glow-xs-purple' },
  rose:   { bgClass: 'bg-rose/12',         textClass: 'text-rose',         dotClass: 'bg-rose',         borderClass: 'border-rose/20',         shadowClass: 'shadow-glow-xs-rose' },
  amber:  { bgClass: 'bg-amber/12',        textClass: 'text-amber',        dotClass: 'bg-amber',        borderClass: 'border-amber/20',        shadowClass: 'shadow-glow-xs-amber' },
  teal:   { bgClass: 'bg-teal/12',         textClass: 'text-teal',         dotClass: 'bg-teal',         borderClass: 'border-teal/20',         shadowClass: 'shadow-glow-xs-teal' },
};
